Repository ucsb-cs156-f23/proj-organic-f23-6pm-4, pull requests merged in 2023-11, with the labels that each got.

#12 Add Instructor Column
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: 5, Merge Candidate

#23 Fixing Typo In Footer
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 5, Merge Candidate

#24 Added ROLE_INSTRUCTOR to SecurityConfig
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
Labels: 5

#25 do - Add Course Form with Storybook and Tests
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/stories/components/Courses/CoursesForm.stories.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
Labels: Merge Candidate, 10

#37 do - Add Courses Navigation
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/stories/components/Nav/AppNavbar.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: Merge Candidate, 10

#42 Deploy organic and organic-qa in dokku and Update dokku link in README
  README.md
Labels: 5, Merge Candidate

#43 Added Courses Tables
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Utils/CoursesUtils.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/components/Utils/CoursesUtils.test.js
Labels: Merge Candidate, 10

#33 #11/F1: Add Schools Fixtures
  frontend/src/fixtures/schoolsFixtures.js
Labels: 5, Merge Candidate

#40 B1.A Backend PUT operations on Course Controller for Courses, Course Staff
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/StaffRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: Merge Candidate, 10

#48 cs - Issue #11/F1: Created Schools Form
  frontend/src/main/components/School/SchoolForm.js
  frontend/src/stories/components/School/SchoolForm.stories.js
  frontend/src/tests/components/School/SchoolForm.test.js
Labels: Merge Candidate, 10

#18 do - Add Toggle Admin/Instructor Buttons
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/AdminUsersPage.js
  frontend/src/main/utils/users.js
  frontend/src/stories/components/Users/UsersTable.stories.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
  frontend/src/tests/utils/users.test.js
Labels: Merge Candidate, 10

#50 cs - Issue #11/F1: Created Schools Table and Tests
  frontend/src/main/components/School/SchoolsTable.js
  frontend/src/main/utils/schoolUtils.js
  frontend/src/stories/components/School/SchoolsTable.stories.js
  frontend/src/tests/components/School/SchoolsTable.test.js
  frontend/src/tests/utils/schoolUtils.test.js
Labels: 10

#51 Course Edit Page with tests and stories
  frontend/src/App.js
  frontend/src/main/pages/CoursesEditPage.js
  frontend/src/stories/pages/CoursesEditPage.stories.js
  frontend/src/tests/pages/CoursesEditPage.test.js
Labels: Merge Candidate, 10

#52 CourseIndexPage and tests
  frontend/src/App.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/pages/CourseIndexPage.js
  frontend/src/stories/pages/CourseIndexPage.stories.js
  frontend/src/tests/pages/CourseIndexPage.test.js
Labels: Merge Candidate, 10
